language: node_js
node_js:
  - 16

services:
  - docker

script:
  ## Build
  - echo 'beginning build'
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  ## Tagging
  - docker tag udagram-api-feed quanhh85/udagram-api-feed:latest
  - docker tag udagram-api-user quanhh85/udagram-api-user:latest
  - docker tag udagram-frontend quanhh85/udagram-frontend:latest
  - docker tag reverseproxy quanhh85/reverseproxy:latest
after_success:
  ## Login
  - echo 'beginning login'
  ## Login to Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  ## Push
  - echo 'beginning push image'
  - docker push quanhh85/udagram-api-feed
  - docker push quanhh85/udagram-api-user
  - docker push quanhh85/udagram-frontend
  - docker push quanhh85/reverseproxy
